name: "Voyanti Victron Addon"
description: "Voyanti Victron Addon"
version: "0.1.54"
slug: "victron"
url: "https://github.com/octoco-ltd/voyanti-ha-victron"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

uart: true
usb: true
startup: system
boot: auto

options:
  inverter_model: "Quattro 48/10000"
  cerbo_model: "Cerbo GX"
  ha_mqtt_host: "localhost"
  ha_mqtt_port: 1883
  ha_mqtt_user: "mqtt"
  ha_mqtt_password: "yourmqttpassword"
  cerbo_mqtt_host: "victron.local"
  cerbo_mqtt_port: 1883
  cerbo_mqtt_user: ""
  cerbo_mqtt_password: ""
  cerbo_serial_no: "1234567890"
  solarchargers:
    - id: "0"
      name: "MPPT 1"
      model: "MPPT 250-100"
  grid_meters:
    - id: "30"
      name: "Grid Meter"
      model: "ET340"
  debug: 2
schema:
  ha_mqtt_host: str
  ha_mqtt_port: int
  ha_mqtt_user: str
  ha_mqtt_password: password
  cerbo_mqtt_host: str
  cerbo_mqtt_port: int
  cerbo_mqtt_user: str?
  cerbo_mqtt_password: password?
  cerbo_serial_no: str
  inverter_model: str
  cerbo_model: str
  solarchargers:
    - id: str
      name: str
      model: str
  grid_meters:
    - id: str
      name: str
      model: str
  DEBUG: int(0,5)
      